sources:
  - type: local
    path: "./data/input_files"

  - type: api
    url: "http://localhost:5000/api/data"
    auth_token: "xyz123"
    folder_param: "./data/api"

target:
  type: postgres
  host: "localhost"
  port: 5432
  database: "elt_db"
  user: "elt_user"
  password: "elt_password"
  table: "raw_data"
