sources:
  - type: local
    path: "./data/input_files"

  - type: api
    url: "http://localhost:5000/api/data"
    auth_token: "xyz123"
    folder_param: "./data/api_std_schema"

target:
  type: postgres
  host: "localhost"
  port: 5432
  database: "elt_db"
  user: "elt_user"
  password: "elt_password"
  table: "config_w_schema_data_wo_schema"

schema:
  columns:
    id: int64
    name: object
    role: object

strict_mode: true
